version: '3.7'
services:
  router:
    image: "traefik:v2.3"
    command:
      - --api.insecure=false # set to 'false' on production
      - --api.dashboard=true # see https://docs.traefik.io/v2.0/operations/dashboard/#secure-mode for how to secure the dashboard
      - --entrypoints.web.address=:80
        #- --entrypoints.web.http.redirections.entryPoint.to=websecure
        #- --entrypoints.web.http.redirections.entryPoint.scheme=https
        #- --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
        #- --traefik.http.routers.redirs.rule=hostregexp(`{host:plantuml.+}`)  
        #- --traefik.http.routers.redirs.entrypoints=web
        #- --traefik.http.routers.redirs.middlewares=redirect-to-https
      - --providers.docker
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedbydefault=false
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./configuration/:/configuration/"
      - "/etc/ssl/:/etc/ssl/"
    networks:
      - factory-plus
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dashboard.rule=Host(`traefik.amrc-factoryplus.***REMOVED***`)"
        - "traefik.http.routers.dashboard.tls=true"
        - "traefik.http.services.justAdummyService.loadbalancer.server.port=1337"
        - "traefik.http.routers.dashboard.service=api@internal"
        - "traefik.http.routers.dashboard.middlewares=auth"
        - "traefik.http.middlewares.auth.basicauth.users=admin:$$apr1$$xltPFC2H$$9PDTfQqY9IWvRlxEdqI9o0"
      placement:
        constraints:
          - node.hostname == amrc-factoryP-1
networks:
  factory-plus:
    external: true
    name: factory-plus
